### ISSUE TITLE
@guildedjs/gil tasks not a folder in node_modules

### ISSUE THREAD

**Issue by tovade** [zaida04/guilded.js#142]
**Describe the bug**
When using @guildedjs/gil you get the following error: ```projects\bob\node_modules\@guildedjs\gil\dist\tasks. To make this warning go away, simply create the folder in your src folder.```
**To Reproduce**

1. Setup a project using guilded.js/gil
2. Start the project
3. See error in terminal

**Expected behavior**
Runs fine no warnings about the node_modules folder

**Screenshots**

**Please complete the following information**

-   NodeJS version: v16.15.1
-   NPM version: 8.4.0
-   Package version: 0.13.0

**Additional context**
No.

**Comment by tovade** [comment]
This seems only to be a warning and not an error

**Comment by Uhuh** [comment]
Mind sharing a screenshot and how you're using `gil`? Can't seem to replicate this.

**Comment by tovade** [comment]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/66245404/174130867-796809a3-8f7d-4450-aae3-8502ea10074b.png">
<img width="955" alt="image" src="https://user-images.githubusercontent.com/66245404/174130984-11f89dc4-2f23-4e59-9022-76ee2f549269.png">

**Comment by Uhuh** [comment]
Ah okay, I'm seeing the issue. I'll flag this. Thanks.

**Comment by tovade** [comment]
> Ah okay, I'm seeing the issue. I'll flag this. Thanks.

What does it seem to be?

**Comment by Uhuh** [comment]
> What does it seem to be?

We check your `src` folder for the prompted folders, however _we're_ missing a `tasks` folder so it's complaining that that it's missing from our `dist`. It's not breaking as far as a know so for now it's not breaking your bot.

If it is let us know.

**Comment by tovade** [comment]
Ah, ok. It isn't breaking my bot so its fine.

**Comment by DaStormer** [comment]
I believe #147 fixes this. Thanks for reporting!
