### ISSUE TITLE
doc

### ISSUE THREAD

**Issue by Erkalos** [zaida04/guilded.js#148]
Hi there,

I just don't know where is the documentation.
The home page redirect on itself for the documentation.

So,  where is the doc ? :)

**Comment by DaStormer** [comment]
hey @Erkalos,

the documentation can be found here: https://guilded.js.org/

navigate to one of the modules to view its docs

direct link to guilded.js docs: https://guilded.js.org/modules/guilded_js_lib.html

**Comment by totallytavi** [comment]
If possible, could we remove the `/lib` at the end? These may confuse users and I had a small issue with it.
<img width="361" alt="image" src="https://user-images.githubusercontent.com/66774833/175184240-05c7fd0b-e4b7-4882-9980-771fd83af512.png">
Also, this is what Discord.js does and it makes it understandable. Still, this is a suggestion.
<img width="279" alt="image" src="https://user-images.githubusercontent.com/66774833/175184362-835d16a4-16ec-4068-80e9-b67a1a0864df.png">

**Comment by zaida04** [comment]
We can certainly try to get the /lib removed, something to do with the tool we use to generate documentation (tsdoc). As for the dropdown menu, we don’t have the resources right now to spend time creating our own theme for tsdoc that implements that, so for now it’s on the back burner.1

**Comment by totallytavi** [comment]
Wasn't looking for the drop down but that'd be nice to have. Would community edits be preferred or should we expect a package to do it? (I've done some research and I can't find a way to remove the `/lib` even with renaming the folders)

**Comment by zaida04** [comment]
Could you elaborate what you mean by community edits?

**Comment by totallytavi** [comment]
The community provides documentation.

**Comment by totallytavi** [comment]
Alternatively, we could utilize the definitions provided in the JS tags for documentation
```js
/**
  * @param {string} world World
  */
function(world) {
  console.log(`Hello ${world}`);
}
```

**Comment by zaida04** [comment]
I don’t seem to understand, we already generate documentation from those tags. You can see it at https://guilded.js.org

**Comment by totallytavi** [comment]
Interested on how Discord.js does it because they lose the `/lib`

Edit: They have a package that generates doc JSON files. Looking into using this on Guilded

**Comment by zaida04** [comment]
The `/lib` has been dropped.
