### ISSUE TITLE
Add support for mentions

### ISSUE THREAD

**Issue by WrenchX** [zaida04/guilded.js#177]
**Is your feature request related to a problem? Please describe.**
Guilded.js doesn't support https://www.guilded.gg/docs/api/channels/Mentions, which I need for my bot

**Describe the solution you'd like**
Support it

**Describe alternatives you've considered**
*shrug*

**Additional context**
Add it and add it to massage content so I can send it with my embed.

**Comment by zaida04** [comment]
Does https://guilded.js.org/classes/guilded_js.Message.html#mentions not suffice?

**Comment by WrenchX** [comment]
> Does https://guilded.js.org/classes/guilded_js.Message.html#mentions not suffice?

Not really, since to send a message using https://guilded.js.org/classes/guilded_js.GlobalMessageManager.html#send, it needs to fit https://guilded.js.org/types/guilded_js.MessageContent.html, which _doesn't_ have Mentions

**Comment by zaida04** [comment]
Ohh, you are referring to _sending_ a message with mentions. That's a limitation of the Guilded API, not the library. The API doesn't support plaintext mentions as of yet, **unless they are contained in an embed**.

**Comment by zaida04** [comment]
Closing as there have been no further comments.
