### ISSUE TITLE
WebhookClient throws error if masquerade isn't provided.

### ISSUE THREAD

**Issue by williamhorning** [zaida04/guilded.js#182]
**Describe the bug**
When creating an instance of WebhookClient without providing a masquerade, an error is thrown.

**To Reproduce**

1. Run the following code on the latest version of guilded.js
```js
import { Client as GuildedClient, WebhookClient } from "guilded.js";
let hook = new WebhookClient({id: "abc", token: "123"})
await hook.send({content: "hello"})
```
2. See the following error thrown:
```
C:\Users\william\Projects\bolt\node_modules\@guildedjs\webhook-client\dist\WebhookClient.js:7
    constructor(webhookConnection, { username, avatarURL }) {
                                     ^

TypeError: Cannot destructure property 'username' of 'undefined' as it is undefined.
    at new WebhookClient (C:\Users\william\Projects\bolt\node_modules\@guildedjs\webhook-client\dist\WebhookClient.js:7:38)
    at guildedClient.bridgeSend (file:///C:/Users/william/Projects/bolt/platforms/guilded.js:123:14)
    at client.bridgeSend (file:///C:/Users/william/Projects/bolt/class.js:252:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.7.0
```

**Expected behavior**
This should not be thrown, as providing a masquerade in the constructor should be optional.

**Please complete the following information**

- Node.js version: 18.7.0
- npm version: 8.15.0
- Package version: 0.13.16

**Additional context**
I can't repro this on 0.13.8

**Comment by zaida04** [comment]
Thanks for the report! We'll have a fix for this out later.

**Comment by zaida04** [comment]
Turns out, this is actually already tackled in #181. Upon release of that PR, this issue should be fixed.
