### ISSUE TITLE
Websocket Ping is sometimes null

### ISSUE THREAD

**Issue by FirephoenixX02** [zaida04/guilded.js#191]
**Describe the bug**
Websocket Ping is sometimes null

**To Reproduce**
Try to print out Websocket ping (client.ws.ping)

**Expected behavior**
The correct ping instead of null.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/81097492/203593821-2055df8d-3cb5-4d0c-8b51-af7f933a37b0.png)

**Please complete the following information**

-   NodeJS version (`node -v`) v18.4.0
-   NPM version (`npm -v`) 8.18.0
-   Package version (`npm ls guilded.js`) guilded.js@0.13.24

**Additional context**
-

**Comment by zaida04** [comment]
closed by df34514295d2fce5f9901ae6360bf59ed9a0d041
