### ISSUE TITLE
msg.author and msg.member are always null

### ISSUE THREAD

**Issue by FirephoenixX02** [zaida04/guilded.js#192]
**Describe the bug**
msg.author and msg.member are always null.

**To Reproduce**
Try to access msg.author or msg.member

**Expected behavior**
That the author and member are not null and return the right user object.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/81097492/203799319-7681c20a-a28e-40de-b511-9fa970c65c1b.png)

![grafik](https://user-images.githubusercontent.com/81097492/203799137-3b2d2adc-97a5-4144-bdba-8c2741e8abc4.png)

**Please complete the following information**

-   NodeJS version (`node -v`) v19.1.0
-   NPM version (`npm -v`) 8.19.3
-   Package version (`npm ls guilded.js`) guilded.js@0.13.24

**Additional context**
-

**Comment by zaida04** [comment]
This is intentional. Guilded does not give us message author or member data on the message event, so it's null. You can refer to this doc for what you can do to get around this: https://www.guilded.gg/guildedjs/groups/G3p7OAgz/channels/4641eb32-4547-4e36-bbc2-55d6780d44ca/docs/318013

**Comment by FirephoenixX02** [comment]
> This is intentional. Guilded does not give us message author or member data on the message event, so it's null. You can refer to this doc for what you can do to get around this: https://www.guilded.gg/guildedjs/groups/G3p7OAgz/channels/4641eb32-4547-4e36-bbc2-55d6780d44ca/docs/318013

Weird but ok
