### ISSUE TITLE
Add function(s) for getting emojis and roles in a server

### ISSUE THREAD

**Issue by chill31** [zaida04/guilded.js#200]
I was creating a server info command, and everything was going well, until I wanted to show the amount of roles and emotes, it's not really necessary to add, but how else would a general member know about it? I would want my bot to show all valid information to be shown so the user can actually get to know something when they run the command.

maybe like the `<members>.fetchMany(serverId)` function, there should be the same for emotes and roles
for example:
`await client.roles.fetchMany(serverId)`
`await client.emotes.fetchMany(serverId)`

There are literally no alternatives possible, there are no role/emote function matching my use, there are only functions to add roles to user or remove roles from user.

Like all the other `fetchMany()` functions, these both should return useful information like:

- whether the emote is animated or not
- emote id
- emote creation date/time
- role id
- role permissions list
- role created date/time

the animated boolean is a must.

**Comment by zaida04** [comment]
This is a limitation of the Guilded API. Once the API supports it, we will too. Feel free to reopen when the time comes.

**Comment by chill31** [comment]
ok I have written a form to the API for adding this feature, hope they check it out and add it
