### ISSUE TITLE
Send images

### ISSUE THREAD

**Issue by ssamachi** [zaida04/guilded.js#201]
Can I send or upload an image to a guilded channel? Using this library?

**Comment by zaida04** [comment]
Guilded only supports uploading an image through a webhook in the API. 

If you have an already uploaded image from another CDN, you can use an embed to send the image to the channel.

**Comment by ssamachi** [comment]
> Guilded only supports uploading an image through a webhook in the API.
> 
> If you have an already uploaded image from another CDN, you can use an embed to send the image to the channel.

I see. Using the webhook when I send a large image it returns an image with smaller resolution. Do you know why that happens?

**Comment by zaida04** [comment]
That is likely an issue with either the image being passed in or the CDN resizing it.

**Comment by zaida04** [comment]
Closing, feel free to reopen if this issue isn't solved.
