### ISSUE TITLE
Optional parameters are displayed as required parameters.

### ISSUE THREAD

**Issue by AusKarlos87** [zaida04/guilded.js#206]
**Describe the bug**
A QoL bug fix. Many of the methods used throughout the GlobalManagers have optional parameters for example` client.members.fetch(serverId: string, memberId: string, force?: boolean) `. Within the docs it makes it look like the `force` parameter is required.

 Go to https://guilded.js.org/docs/guilded.js/GlobalMemberManager#fetch

**Expected behavior**
Clearly defined optional parameters

**Comment by zaida04** [comment]
I've temporarily shelved the custom docs until we have someone that can work on making them more stable.
