### ISSUE TITLE
[ Deleted ]

### ISSUE THREAD

**Issue by S8hUGqihmLURd0DP** [zaida04/guilded.js#207]
[ Deleted ]

**Comment by zaida04** [comment]
Hey, guilded.js does infact support forum topic comment creation: https://guildedjs.github.io/classes/guilded_js.GlobalForumTopicManager.html#createForumTopic

**Comment by zaida04** [comment]
For further note, if the API ever has anything that we don't have directly integrated, you can use the client rest manager (client.rest) to make the HTTP requests yourself ahead of our implementation.

**Comment by Archius0** [comment]
> Hey, guilded.js does infact support forum topic comment creation: https://guildedjs.github.io/classes/guilded_js.GlobalForumTopicManager.html#createForumTopic

I have no idea how I managed to overlook that one, cheers!

**Comment by zaida04** [comment]
Taking another look, I think I made a mistake here! I linked you the docs for forum _topic_ creation, not forum topic _comment_ creation.

**Comment by Archius0** [comment]
Can confirm; I thought that comment creation used the same method so I decided to try it. No worries though, I'll use the `client.rest` property in the meantime!
