### ISSUE TITLE
Website Not Responsive if width is below 1000px

### ISSUE THREAD

**Issue by chill31** [zaida04/guilded.js#211]
## Describe the bug
it is not a bug in the actual content, but the responsive website. If viewed below 1000px width, the [https://guilded.js.org/docs/guilded.js](https://guilded.js.org/docs/guilded.js) starts overflowing and text starts overlapping.

## To Reproduce

1. Go to [https://guilded.js.org/docs/guilded.js](https://guilded.js.org/docs/guilded.js)
2. Open dev tools
3. Open responsive thing (whatever it is called to view different heights and widths)
4. Change width to 1000px
5. scroll down a bit and check the text. It is overlapping

## Expected behavior
The text should not be overlapping?
It works fine after **767**px but still, in between **1000** and **767**, the bug is still there.

## Screenshots
<img width="960" alt="Screenshot_20230202_150627" src="https://user-images.githubusercontent.com/89910163/216287620-48812e2d-56ca-403e-8f76-4c659d024d1f.png">

<br>
<br>
<br>

**Please complete the following information**

-   Firefox **109.0**

**Comment by zaida04** [comment]
Thank you for reporting this! We will add this to our bug fixes list and knock it out as soon as possible.

**Comment by zaida04** [comment]
Going to go ahead and close this in accordance with https://github.com/zaida04/guilded.js/issues/206#issuecomment-1560171026
