### ISSUE TITLE
Experimental Fetch API Error

### ISSUE THREAD

**Issue by achille-bosc** [zaida04/guilded.js#237]
**Describe the bug**
When i fetch a message with the "messageCreated" event in TypeScript, I have the following error:
```(node:89895) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```

**To Reproduce**

1. create a "messageCreated" event handler
2. start the code
3. send a message in the same guild where is the bot
4. check the terminal

**Expected behavior**
No Error

**Screenshots**
![Capture d’écran 2023-06-28 à 17 12 51](https://github.com/zaida04/guilded.js/assets/136481630/29f3376c-a894-43ad-a6fc-d2153ad604c3)
![Capture d’écran 2023-06-28 à 17 13 09](https://github.com/zaida04/guilded.js/assets/136481630/ad300c1b-5e37-48eb-ad9c-7f7d5769758e)

**Please complete the following information**

-   NodeJS version (`node -v`) => v18.12.1
-   NPM version (`npm -v`) => 8.19.2
-   Package version (`npm ls guilded.js`) => guilded.js@0.23.2

**Additional context**
/////

**Comment by zaida04** [comment]
That's odd, you shouldn't be getting that error on node 18. Can you confirm the version you're using by doing `console.log(process.version)`?

**Comment by achille-bosc** [comment]
Yes, i confirm
![Capture d’écran 2023-06-28 à 17 59 24](https://github.com/zaida04/guilded.js/assets/136481630/17a39ccc-7fe4-4833-a34d-4a6832f63ba0)

**Comment by achille-bosc** [comment]
I've downloaded the v20.3.1 to overcome this problem
