### ISSUE TITLE
NPM package is missing

### ISSUE THREAD

**Issue by Jernik** [zaida04/guilded.js#45]
**Describe the bug**
[The link in the readme 404s](https://www.npmjs.com/package/guilded.js)

**To Reproduce**

1. Go to https://www.npmjs.com/package/guilded.js

**Expected behavior**
I expect there to be an NPM package there

**Screenshots**
![image](https://user-images.githubusercontent.com/7637894/159998841-d9e42844-5afe-4a46-88cc-39411b27201b.png)

**Please complete the following information**

-   N/A

**Additional context**
I'd like to pull this library in to start developing a bot, but there isn't a package. 
Additionally, going to the [old package](https://www.npmjs.com/package/@guildedjs/guilded.js) has a big red deprecated banner pointing to the same link, which is a 404

**Comment by Henrik-3** [comment]
![image](https://user-images.githubusercontent.com/43936184/160000241-6cee5c13-a248-4441-a7f2-15105c589663.png)

Additional Info: Still available to find over https://www.npmjs.com/search?q=guilded

**Comment by Jernik** [comment]
when I try to install it from a cli:
![image](https://user-images.githubusercontent.com/7637894/160002543-82f3b87a-2a3c-4493-a265-6eee1c7c3225.png)

**Comment by zaida04** [comment]
Fixed, NPM cache was not propagating with version `0.2.0`, making the package not discoverable. Published `0.2.1`, and that seemed to fix the issue. Thanks for bringing this to our attention!
